mrc-3001 only return state from run for given index
mrc-ide/mode pull request #10
Opened 2022-03-30 14:36 UTC by hillalex

`mod$state` still returns the full state, and `mod$update_state` still expects the full state, but `mod$run` only returns state for indices set in `mod$set_index` - not sure if it will be useful to be able to update and retrieve state based on the index as well?

2022-03-30 14:38 UTC, hillalex commented on inst/include/mode/r/mode.hpp
> +int r_index_check(int x, int max) {
these helpers lifted straight from dust. wonder if it's time to put utils in a separate file

2022-03-30 15:05 UTC, richfitz requested changes

2022-03-30 15:05 UTC, richfitz commented on inst/include/mode/r/mode.hpp
> +int r_index_check(int x, int max) {
yeah, I think that would be good

2022-03-30 15:05 UTC, richfitz commented on tests/testthat/test-interface.R
> +  expect_identical(res, state[1, , drop = F])
```suggestion
  expect_identical(res, state[1, , drop = FALSE])
```

Traumatically, `F <- TRUE` is valid while `FALSE <- TRUE` is a syntax error.

2022-03-30 15:05 UTC, richfitz commented on tests/testthat/test-interface.R
> +})
Can you expand the testing here to check that we can use an index of length > 1 and error if given out of range values (0 or too large)

2022-03-30 15:05 UTC, richfitz commented on tests/testthat/test-interface.R
> +})
Also, I think that setting an index of `NULL` should wipe the index - that should be tested too.

Edit: looks like dust does not support that actually, but it should!

2022-03-30 15:05 UTC, richfitz commented on inst/template/mode.R.template
> +    set_index = function(index) {
For compatibility with dust, can you add a trivial getter here too?

```
index = function() {
  private$index_
}
```

2022-03-30 15:05 UTC, richfitz commented on inst/template/mode.R.template
> +    index_ = NULL
It's not in the diff, but the solve method should be updated to do:

```
    m <- mode_logistic_solve(private$ptr_, end_time)
    rownames(m) <- names(private$index_)
    m
```

which allows a named index to be set (e.g., `set_index(c(I = 2, R = 3))`) and named output to be returned.

We should also rename solve -> run at some point I think...

2022-03-30 15:14 UTC, hillalex commented on inst/template/mode.R.template
> +    index_ = NULL
https://github.com/mrc-ide/mode/pull/11

2022-03-31 08:52 UTC, richfitz approved these changes

2022-03-31 08:53 UTC, merged