add output fn
mrc-ide/mode pull request #17
Opened 2022-04-21 12:23 UTC by hillalex

2022-04-25 12:48 UTC, hillalex commented on inst/include/mode/mode.hpp
> +    return m_.size() + m_.n_output();
Have renamed these to distinguish between total output including derived values, and just the model size. Not sure about these names though, thoughts?

2022-04-25 12:48 UTC, hillalex commented on inst/template/mode.R.template
> +      dim_state <- dim(state)
Here just dropping extra values/columns if a vector or matrix corresponds to the full output size, but leaving all other validation to the c++ layer as before. So also not sure whether this splitting of validation logic makes sense, but it keeps the changes here to a minimum.

2022-04-25 16:55 UTC, richfitz requested changes
I've had a think about this and apologise for what looks like some false leads I've suggested. Below is a proposal that might help simplify this by tidying up the names and centralising into `stepper` the control over these things. We talked before about separation of concerns in terms of who knows about the model, and I am fairly sure that in the end we can end up with only the stepper holding a persistent copy of an initialised model object - this refactor should help with that.

Happy to discuss further tomorrow as this has raised way ambiguous bits than I was expecting

----

I think that we might refer to a few things

* deterministic - the things that enter into the ODEs
* stochastic - the things that enter into the stochastic update
* variables - the set of deterministic + stochastic
* output - quantities derived from the above at the point of reporting
* state_full - variables + output
* state_run - filtered state from run

We always pack our variables so that they are deterministic followed by stochastic, and so we can exclude the stochastic variables from the error calculation eventually.  Or we could leave this distinction as a detail.

Our model then provides methods:

```
size_t n_variables() const;
```

The number of deterministic and stochastic variables

```
size_t n_output() const;
```

Returns the number of outputs

```
void rhs(double t,
         const std::vector<double>& y,
         std::vector<double>& dydt);
```

`y` and `dydt` are length `n_variables`

```
void output(double t, 
            const std::vector<double>& y,
            std::vector<double>& output);
```

`y` is a vector of length `n_variables` and `output` is a vector of length `n_outputs` (sorry, see below for getting this working).

I think that the stepper can lose the `state_full_`, but pick up a small vector `output_` which is of length `n_outputs()`

We'll need to reflect these changes out into the `solver` object (replacing `size_` with `n_variables_` and `n_output_`.

More complicated on the `container` object though because this has the default `index` set which controls what is returned when we call `run()`

So that then ends up with methods 

* `n_variables()`:, i.e., what does the model need to start up
* `n_outputs()`: The number of additional outputs
* `n_state_full`: `n_variables() + n_outputs()`
* `n_state_run`: Filtered state, on [0, `n_state_full()`]

Then our interface run method looks like:

```
template <typename T>
cpp11::sexp mode_run(SEXP ptr, double end_time) {
  T *obj = cpp11::as_cpp<cpp11::external_pointer<T>>(ptr).get();
  auto time = obj->time();
  if (end_time < time) {
    cpp11::stop("'end_time' (%f) must be greater than current time (%f)",
                end_time, time);
  }
  obj->run(end_time);

  // these 3 change minimally:
  std::vector<double> dat(obj->n_state_run() * obj->n_particles());
  obj->state_run(dat);
  return mode::r::state_array(dat, obj->n_state_run(), obj->n_particles());
}
```

The `solver::state()` method needs changing then

```
  std::vector<double>::iterator
  state(const std::vector<size_t>& index,
             std::vector<double>::iterator end_state) {
    return stepper_.state(it, index);
  }
```

And the stepper (which is the thing that actually holds the model object - and I think we can reduce to just this holding it)

```
  void state(std::vector<double>::iterator end_state) {
    const n_variables = m_.n_variables();
    bool have_run_output = false;
    for (size_t i = 0; i < n; ++i, ++end_state) {
      if (i < n_variables) {
        *end_state = y[i];
      } else {
        if (!have_run_output) {
          m_.output(t_, y, output);
          have_run_output = true;
        }
        *end_state = output[i - n_variables];
      }
    }
  }
```

2022-04-25 16:55 UTC, richfitz commented on inst/examples/logistic.cpp
> +  output(double t,
This looks like its setting the variables as well as the output - I think that we want the mode function doing the first part

2022-04-25 16:55 UTC, richfitz commented on inst/include/mode/mode.hpp
> +  size_t n_output() const {
I think that `n_state_index` or `n_state_run` or something might capture this one best - it's the number of state variables that we will return when running the model due to the index and is capped as the total of state + output. If we come up with something good here we should backport to dust

2022-04-25 16:55 UTC, richfitz commented on inst/include/mode/mode.hpp
> +  size_t n_output() const {
Possibly if we introduce `n_variables` as a term we can make this work

2022-04-25 16:55 UTC, richfitz commented on inst/template/mode.R.template
> +      dim_state <- dim(state)
I'd prefer this in the C++ (mostly because that's the pattern that we've followed in dust) but also happy to defer moving it there until later

2022-04-25 16:55 UTC, richfitz commented on inst/include/mode/solver.hpp
> +    auto it = state_full_.begin();
There's definitely more churn of data here than we need

2022-04-25 16:55 UTC, richfitz commented on inst/include/mode/solver.hpp
> +    m_.output(t_, it);
We can move to only the stepper holding `m_` which would be preferable - so this definitely needs moving deeper

2022-04-26 15:52 UTC, richfitz reviewed
This looks good - you said

> [11:24] Hill, Alexandra E
I'll also move that logic about dropping output values on a state update from the R to the c++

did you want to do that in this PR or a following one?

2022-04-26 15:52 UTC, richfitz commented on inst/include/mode/solver.hpp
> -    m_ = m;
nice

2022-04-27 08:46 UTC, hillalex commented
> did you want to do that in this PR or a following one?

I'll add here

2022-04-27 12:49 UTC, hillalex commented
this code is confusing and fiddly. is there a better way?!

2022-05-12 14:51 UTC, richfitz approved these changes

2022-05-12 14:52 UTC, merged