mrc-3154
mrc-ide/mode pull request #21
Opened 2022-05-19 12:13 UTC by hillalex

2022-05-19 16:33 UTC, richfitz requested changes

2022-05-19 16:33 UTC, richfitz commented on tests/testthat/test-interface.R
> +pars <- list(r1 = 0.1, r2 = 0.2, K1 = 100, K2 = 100)
You might combine this within a helper-mode.R file as something like:

```
example_logistic <- function() {
  list(generator =   mode(mode_file("examples/logistic.cpp"), quiet = TRUE),
       pars = list(r1 = 0.1, r2 = 0.2, K1 = 100, K2 = 100))
}
```

and avoid this loose `pars` object that feels like it might confuse subsequent tests

2022-05-23 08:58 UTC, hillalex commented on tests/testthat/test-interface.R
> +pars <- list(r1 = 0.1, r2 = 0.2, K1 = 100, K2 = 100)
ah great, thanks

2022-05-23 09:34 UTC, richfitz approved these changes

2022-05-23 09:34 UTC, merged